-- =============================================================================
-- Base de datos: BIBLIOWEB en MYSQL
-- Fecha de creación: 24/01/2023
-- Descripción: Base de datos relacional del sistema web de libros, "Biblioweb".
-- =============================================================================

-- /////////////////////////////////////////CREACION DE LAS TABLAS

-- ##TABLAS, SEC.1 = DATA DEL USUARIO

CREATE TABLE PERSONAS_PERFIL(
	CODIGOPE VARCHAR(10),
    NOMBRES VARCHAR(50),
	APELLIDOS VARCHAR(50),
	GENERO VARCHAR(15),
	FECH_NACIMIENTO VARCHAR(15),
	FOTOGRAFIA VARCHAR(50)
);

ALTER TABLE PERSONAS_PERFIL ADD CONSTRAINT PK_CODIGOPE PRIMARY KEY (CODIGOPE);

CREATE TABLE ROLES(
	CODIGOROL VARCHAR(10),
	NOMBRE VARCHAR(50)
);

ALTER TABLE ROLES ADD CONSTRAINT PK_CODIGOROL PRIMARY KEY (CODIGOROL);

CREATE TABLE USUARIOS(
	CODIGOUS VARCHAR(10),
	USERNAME VARCHAR(20),
	EMAIL VARCHAR(255),
	PASSWORD VARCHAR(30),
	CODIGOPE VARCHAR(10)
);

ALTER TABLE USUARIOS ADD CONSTRAINT PK_CODIGOUS PRIMARY KEY (CODIGOUS);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_CODIGOPE FOREIGN KEY (CODIGOPE) REFERENCES PERSONAS_PERFIL(CODIGOPE);
ALTER TABLE USUARIOS ADD CONSTRAINT UK_CODIGOPE UNIQUE (CODIGOPE);

CREATE TABLE USUARIOS_ROLES(
	CODIGOUS VARCHAR(10) NOT NULL,
	CODIGOROL VARCHAR(10) NOT  NULL
);

ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT PK_CODIGOUSROL PRIMARY KEY (CODIGOUS, CODIGOROL);
ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT FK_USROL_CODIGOUS FOREIGN KEY (CODIGOUS) REFERENCES USUARIOS (CODIGOUS);
ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT FK_USROL_CODIGOROL FOREIGN KEY (CODIGOROL) REFERENCES ROLES (CODIGOROL);

-- ##TABLAS, SEC.2 = DATA DEL SISTEMA DE LIBROS

CREATE TABLE AUTORES(
	CODIGOAUT VARCHAR(10),
	NOMBRES VARCHAR(50),
	APELLIDOS VARCHAR(50),
	FECH_NACIMIENTO VARCHAR(15),
	FOTOGRAFIA VARCHAR(50),
	EXTRA_INFO VARCHAR(255)
);

ALTER TABLE AUTORES ADD CONSTRAINT PK_CODIGOAUT PRIMARY KEY (CODIGOAUT);

CREATE TABLE EDITORIALES(
	CODIGOEDI VARCHAR(10),
	NOMBRE VARCHAR(100)
);

ALTER TABLE EDITORIALES ADD CONSTRAINT PK_CODIGOEDI PRIMARY KEY (CODIGOEDI);

CREATE TABLE GENEROS(
	CODIGOGEN VARCHAR(10),
	NOMBRE VARCHAR(50)
);

ALTER TABLE GENEROS ADD CONSTRAINT PK_CODIGOGEN PRIMARY KEY (CODIGOGEN);

CREATE TABLE LIBROS(
	CODIGOLIB VARCHAR(10),
	NOMBRE VARCHAR(255),
	EDICION VARCHAR(50),
	LUGAR_PUBLICACION VARCHAR(150),
	FECH_PUBLICACION VARCHAR(15),
	PAGINAS VARCHAR(10),
	CODIGOEDI VARCHAR(10)
);

ALTER TABLE LIBROS ADD CONSTRAINT PK_CODIGOLIB PRIMARY KEY (CODIGOLIB);
ALTER TABLE LIBROS ADD CONSTRAINT FK_CODIGOEDI FOREIGN KEY (CODIGOEDI) REFERENCES EDITORIALES (CODIGOEDI);

CREATE TABLE LIBROS_GENEROS(
	CODIGOLIB VARCHAR(10) NOT NULL,
	CODIGOGEN VARCHAR(10) NOT NULL
);

ALTER TABLE LIBROS_GENEROS ADD CONSTRAINT PK_CODIGOLIBGEN PRIMARY KEY (CODIGOLIB, CODIGOGEN);
ALTER TABLE LIBROS_GENEROS ADD CONSTRAINT FK_LIBGEN_CODIGOLIB FOREIGN KEY (CODIGOLIB) REFERENCES LIBROS (CODIGOLIB);
ALTER TABLE LIBROS_GENEROS ADD CONSTRAINT FK_LIBGEN_CODIGOGEN FOREIGN KEY (CODIGOGEN) REFERENCES GENEROS (CODIGOGEN);

CREATE TABLE LIBROS_AUTORES(
	CODIGOLIB VARCHAR(10) NOT NULL,
	CODIGOAUT VARCHAR(10) NOT NULL
);

ALTER TABLE LIBROS_AUTORES ADD CONSTRAINT PK_CODIGOLIBAUT PRIMARY KEY (CODIGOLIB, CODIGOAUT);
ALTER TABLE LIBROS_AUTORES ADD CONSTRAINT FK_LIBAUT_CODIGOLIB FOREIGN KEY (CODIGOLIB) REFERENCES LIBROS (CODIGOLIB);
ALTER TABLE LIBROS_AUTORES ADD CONSTRAINT FK_LIBAUT_CODIGOGEN FOREIGN KEY (CODIGOAUT) REFERENCES AUTORES (CODIGOAUT);

-- ##TABLAS, SEC.3 = DATA DE FAVORITOS, INTERSECCION ENTRE LIBROS Y PERSONAS_PERFIL DE USUARIOS

CREATE TABLE FAVORITOS_LIBPER(
	CODIGOUS VARCHAR(10),
	CODIGOLIB VARCHAR(10)
);

ALTER TABLE FAVORITOS_LIBPER ADD CONSTRAINT PK_CODIGOPELIB PRIMARY KEY (CODIGOUS, CODIGOLIB);
ALTER TABLE FAVORITOS_LIBPER ADD CONSTRAINT FK_PELIB_CODIGOUS FOREIGN KEY (CODIGOUS) REFERENCES USUARIOS (CODIGOUS);
ALTER TABLE FAVORITOS_LIBPER ADD CONSTRAINT FK_PELIB_CODIGOLIB FOREIGN KEY (CODIGOLIB) REFERENCES LIBROS (CODIGOLIB);

commit;

UPDATE sqcName SET next_val = next_val + 1;

select * from autores;
select * from editoriales;
select * from favoritos_libper;
select * from generos;
select * from libros;
select * from personas_perfil;
select * from libros_autores;
select * from roles;
select * from usuarios;
select * from usuarios_roles;

select*from personas_perfil_seq;
select*from usuarios_seq;

delete from usuarios;
delete from personas_perfil;
