-- =============================================================================
-- Base de datos: BIBLIOWEB
-- Fecha de creación: 16/08/2023
-- Descripción: Base de datos relacional del sistema web de libros, "Biblioweb".
-- =============================================================================

-- /////////////////////////////////////////CREACION DE LAS TABLAS

-- ##TABLAS, SEC.1 = DATA DEL USUARIO
 
CREATE TABLE PERSONAS_PERFIL(
CODIGOPE VARCHAR2(10),
NOMBRES VARCHAR2(50),
APELLIDOS VARCHAR2(50),
GENERO VARCHAR2(15),
FECH_NACIMIENTO VARCHAR2(15),
FOTOGRAFIA VARCHAR2(50)
);

ALTER TABLE PERSONAS_PERFIL ADD CONSTRAINT PK_CODIGOPE PRIMARY KEY (CODIGOPE);

CREATE TABLE ROLES(
CODIGOROL VARCHAR2(10),
NOMBRE VARCHAR2(50)
);

ALTER TABLE ROLES ADD CONSTRAINT PK_CODIGOROL PRIMARY KEY (CODIGOROL);

CREATE TABLE USUARIOS(
CODIGOUS VARCHAR2(10),
USERNAME VARCHAR2(20),
EMAIL VARCHAR2(255),
PASSWORD VARCHAR2(30),
CODIGOPE VARCHAR2(10)
);

ALTER TABLE USUARIOS ADD CONSTRAINT PK_CODIGOUS PRIMARY KEY (CODIGOUS);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_CODIGOPE FOREIGN KEY (CODIGOPE) REFERENCES PERSONAS_PERFIL(CODIGOPE);

CREATE TABLE USUARIOS_ROLES(
CODIGOUS VARCHAR2(10) NOT NULL,
CODIGOROL VARCHAR2(10) NOT  NULL
);

ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT PK_CODIGOUSROL PRIMARY KEY (CODIGOUS, CODIGOROL);
ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT FK_USROL_CODIGOUS FOREIGN KEY (CODIGOUS) REFERENCES USUARIOS (CODIGOUS) ENABLE;
ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT FK_USROL_CODIGOROL FOREIGN KEY (CODIGOROL) REFERENCES ROLES (CODIGOROL) ENABLE;

-- ##TABLAS, SEC.2 = DATA DEL SISTEMA DE LIBROS

CREATE TABLE AUTORES(
CODIGOAUT VARCHAR2(10),
NOMBRES VARCHAR2(50),
APELLIDOS VARCHAR2(50),
FECH_NACIMIENTO VARCHAR2(15),
FOTOGRAFIA VARCHAR2(50),
EXTRA_INFO VARCHAR2(255)
);

ALTER TABLE AUTORES ADD CONSTRAINT PK_CODIGOAUT PRIMARY KEY (CODIGOAUT);

CREATE TABLE EDITORIALES(
CODIGOEDI VARCHAR2(10),
NOMBRE VARCHAR2(100)
);

ALTER TABLE EDITORIALES ADD CONSTRAINT PK_CODIGOEDI PRIMARY KEY (CODIGOEDI);

CREATE TABLE GENEROS(
CODIGOGEN VARCHAR2(10),
NOMBRE VARCHAR2(50)
);

ALTER TABLE GENEROS ADD CONSTRAINT PK_CODIGOGEN PRIMARY KEY (CODIGOGEN);

CREATE TABLE LIBROS(
CODIGOLIB VARCHAR2(10),
NOMBRE VARCHAR(255),
EDICION VARCHAR2(50),
LUGAR_PUBLICACION VARCHAR2(150),
FECH_PUBLICACION VARCHAR(15),
PAGINAS VARCHAR(10),
CODIGOEDI VARCHAR(10)
);

ALTER TABLE LIBROS ADD CONSTRAINT PK_CODIGOLIB PRIMARY KEY (CODIGOLIB);
ALTER TABLE LIBROS ADD CONSTRAINT FK_CODIGOEDI FOREIGN KEY (CODIGOEDI) REFERENCES EDITORIALES (CODIGOEDI);

CREATE TABLE LIBROS_GENEROS(
CODIGOLIB VARCHAR2(10) NOT NULL,
CODIGOGEN VARCHAR2(10) NOT NULL
);

ALTER TABLE LIBROS_GENEROS ADD CONSTRAINT PK_CODIGOLIBGEN PRIMARY KEY (CODIGOLIB, CODIGOGEN);
ALTER TABLE LIBROS_GENEROS ADD CONSTRAINT FK_LIBGEN_CODIGOLIB FOREIGN KEY (CODIGOLIB) REFERENCES LIBROS (CODIGOLIB) ENABLE;
ALTER TABLE LIBROS_GENEROS ADD CONSTRAINT FK_LIBGEN_CODIGOGEN FOREIGN KEY (CODIGOGEN) REFERENCES GENEROS (CODIGOGEN) ENABLE;

CREATE TABLE LIBROS_AUTORES(
CODIGOLIB VARCHAR2(10) NOT NULL,
CODIGOAUT VARCHAR2(10) NOT NULL
);

ALTER TABLE LIBROS_AUTORES ADD CONSTRAINT PK_CODIGOLIBAUT PRIMARY KEY (CODIGOLIB, CODIGOAUT);
ALTER TABLE LIBROS_AUTORES ADD CONSTRAINT FK_LIBAUT_CODIGOLIB FOREIGN KEY (CODIGOLIB) REFERENCES LIBROS (CODIGOLIB) ENABLE;
ALTER TABLE LIBROS_AUTORES ADD CONSTRAINT FK_LIBAUT_CODIGOGEN FOREIGN KEY (CODIGOAUT) REFERENCES AUTORES (CODIGOAUT) ENABLE;

-- ##TABLAS, SEC.3 = DATA DE FAVORITOS, INTERSECCION ENTRE LIBROS Y PERSONAS_PERFIL DE USUARIOS

CREATE TABLE FAVORITOS_LIBPER(
CODIGOUS VARCHAR2(10),
CODIGOLIB VARCHAR2(10)
);

ALTER TABLE FAVORITOS_LIBPER ADD CONSTRAINT PK_CODIGOPELIB PRIMARY KEY (CODIGOUS, CODIGOLIB);
ALTER TABLE FAVORITOS_LIBPER ADD CONSTRAINT FK_PELIB_CODIGOUS FOREIGN KEY (CODIGOUS) REFERENCES USUARIOS (CODIGOUS) ENABLE;
ALTER TABLE FAVORITOS_LIBPER ADD CONSTRAINT FK_PELIB_CODIGOLIB FOREIGN KEY (CODIGOLIB) REFERENCES LIBROS (CODIGOLIB) ENABLE;


COMMIT;